# Generated by Django 3.2.2 on 2021-05-08 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iamuseradditional',
            name='root_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='root_user', to='cloudapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iamuseradditional',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
