# Generated by Django 3.2.2 on 2021-05-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0002_auto_20210509_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Root', 'ROOT'), ('IAM', 'Iam')], default='Root', max_length=255, verbose_name='Type'),
        ),
    ]
