# Generated by Django 3.2.2 on 2021-05-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0004_auto_20210510_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='iamuseradditional',
            name='iam_user_email',
            field=models.EmailField(default='abc@xyz.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='pg', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
