# Generated by Django 3.2.2 on 2021-05-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0005_auto_20210510_1342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iamuseradditional',
            unique_together={('root_user', 'iam_user_email')},
        ),
    ]
